version: '3.8'

services:
  db:
    image: postgres:15
    container_name: clinic_db
    restart: always
    environment:
      POSTGRES_DB: clinic
      POSTGRES_USER: clinic
      POSTGRES_PASSWORD: clinic
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: clinic_app
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/clinic
      SPRING_DATASOURCE_USERNAME: clinic
      SPRING_DATASOURCE_PASSWORD: clinic
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: always

volumes:
  postgres_data:
