--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4 (Debian 17.4-1.pgdg120+2)
-- Dumped by pg_dump version 17.3

-- Started on 2025-03-02 22:40:52

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE clinic;
--
-- TOC entry 3417 (class 1262 OID 16384)
-- Name: clinic; Type: DATABASE; Schema: -; Owner: clinic
--

CREATE DATABASE clinic WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.utf8';


ALTER DATABASE clinic OWNER TO clinic;

\connect clinic

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 3418 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 16390)
-- Name: animals; Type: TABLE; Schema: public; Owner: clinic
--

CREATE TABLE public.animals (
    animal_id bigint NOT NULL,
    animal_name character varying(255),
    type character varying(255),
    owner_id bigint NOT NULL
);


ALTER TABLE public.animals OWNER TO clinic;

--
-- TOC entry 217 (class 1259 OID 16389)
-- Name: animals_animal_id_seq; Type: SEQUENCE; Schema: public; Owner: clinic
--

ALTER TABLE public.animals ALTER COLUMN animal_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.animals_animal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16398)
-- Name: appointments; Type: TABLE; Schema: public; Owner: clinic
--

CREATE TABLE public.appointments (
    id bigint NOT NULL,
    date timestamp(6) without time zone,
    description character varying(255),
    animal_id bigint NOT NULL,
    vet_id bigint NOT NULL
);


ALTER TABLE public.appointments OWNER TO clinic;

--
-- TOC entry 219 (class 1259 OID 16397)
-- Name: appointments_id_seq; Type: SEQUENCE; Schema: public; Owner: clinic
--

ALTER TABLE public.appointments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16404)
-- Name: diagnoses; Type: TABLE; Schema: public; Owner: clinic
--

CREATE TABLE public.diagnoses (
    diagnosis_id bigint NOT NULL,
    description character varying(255),
    name character varying(255)
);


ALTER TABLE public.diagnoses OWNER TO clinic;

--
-- TOC entry 221 (class 1259 OID 16403)
-- Name: diagnoses_diagnosis_id_seq; Type: SEQUENCE; Schema: public; Owner: clinic
--

ALTER TABLE public.diagnoses ALTER COLUMN diagnosis_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.diagnoses_diagnosis_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16412)
-- Name: diagnosis_appointment; Type: TABLE; Schema: public; Owner: clinic
--

CREATE TABLE public.diagnosis_appointment (
    diag_app_id bigint NOT NULL,
    appointment_id bigint NOT NULL,
    diagnosis_id bigint NOT NULL
);


ALTER TABLE public.diagnosis_appointment OWNER TO clinic;

--
-- TOC entry 223 (class 1259 OID 16411)
-- Name: diagnosis_appointment_diag_app_id_seq; Type: SEQUENCE; Schema: public; Owner: clinic
--

ALTER TABLE public.diagnosis_appointment ALTER COLUMN diag_app_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.diagnosis_appointment_diag_app_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16418)
-- Name: roles; Type: TABLE; Schema: public; Owner: clinic
--

CREATE TABLE public.roles (
    role_id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.roles OWNER TO clinic;

--
-- TOC entry 225 (class 1259 OID 16417)
-- Name: roles_role_id_seq; Type: SEQUENCE; Schema: public; Owner: clinic
--

ALTER TABLE public.roles ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16424)
-- Name: users; Type: TABLE; Schema: public; Owner: clinic
--

CREATE TABLE public.users (
    user_id bigint NOT NULL,
    user_description character varying(255),
    user_email character varying(255),
    user_name character varying(255),
    user_password character varying(255),
    user_phone bigint,
    role_id bigint NOT NULL
);


ALTER TABLE public.users OWNER TO clinic;

--
-- TOC entry 227 (class 1259 OID 16423)
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: clinic
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3401 (class 0 OID 16390)
-- Dependencies: 218
-- Data for Name: animals; Type: TABLE DATA; Schema: public; Owner: clinic
--

COPY public.animals (animal_id, animal_name, type, owner_id) FROM stdin;
\.


--
-- TOC entry 3403 (class 0 OID 16398)
-- Dependencies: 220
-- Data for Name: appointments; Type: TABLE DATA; Schema: public; Owner: clinic
--

COPY public.appointments (id, date, description, animal_id, vet_id) FROM stdin;
\.


--
-- TOC entry 3405 (class 0 OID 16404)
-- Dependencies: 222
-- Data for Name: diagnoses; Type: TABLE DATA; Schema: public; Owner: clinic
--

COPY public.diagnoses (diagnosis_id, description, name) FROM stdin;
\.


--
-- TOC entry 3407 (class 0 OID 16412)
-- Dependencies: 224
-- Data for Name: diagnosis_appointment; Type: TABLE DATA; Schema: public; Owner: clinic
--

COPY public.diagnosis_appointment (diag_app_id, appointment_id, diagnosis_id) FROM stdin;
\.


--
-- TOC entry 3409 (class 0 OID 16418)
-- Dependencies: 226
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: clinic
--

COPY public.roles (role_id, name) FROM stdin;
\.


--
-- TOC entry 3411 (class 0 OID 16424)
-- Dependencies: 228
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: clinic
--

COPY public.users (user_id, user_description, user_email, user_name, user_password, user_phone, role_id) FROM stdin;
\.


--
-- TOC entry 3419 (class 0 OID 0)
-- Dependencies: 217
-- Name: animals_animal_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clinic
--

SELECT pg_catalog.setval('public.animals_animal_id_seq', 1, false);


--
-- TOC entry 3420 (class 0 OID 0)
-- Dependencies: 219
-- Name: appointments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clinic
--

SELECT pg_catalog.setval('public.appointments_id_seq', 1, false);


--
-- TOC entry 3421 (class 0 OID 0)
-- Dependencies: 221
-- Name: diagnoses_diagnosis_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clinic
--

SELECT pg_catalog.setval('public.diagnoses_diagnosis_id_seq', 1, false);


--
-- TOC entry 3422 (class 0 OID 0)
-- Dependencies: 223
-- Name: diagnosis_appointment_diag_app_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clinic
--

SELECT pg_catalog.setval('public.diagnosis_appointment_diag_app_id_seq', 1, false);


--
-- TOC entry 3423 (class 0 OID 0)
-- Dependencies: 225
-- Name: roles_role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clinic
--

SELECT pg_catalog.setval('public.roles_role_id_seq', 1, false);


--
-- TOC entry 3424 (class 0 OID 0)
-- Dependencies: 227
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: clinic
--

SELECT pg_catalog.setval('public.users_user_id_seq', 1, false);


--
-- TOC entry 3236 (class 2606 OID 16396)
-- Name: animals animals_pkey; Type: CONSTRAINT; Schema: public; Owner: clinic
--

ALTER TABLE ONLY public.animals
    ADD CONSTRAINT animals_pkey PRIMARY KEY (animal_id);


--
-- TOC entry 3238 (class 2606 OID 16402)
-- Name: appointments appointments_pkey; Type: CONSTRAINT; Schema: public; Owner: clinic
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT appointments_pkey PRIMARY KEY (id);


--
-- TOC entry 3240 (class 2606 OID 16410)
-- Name: diagnoses diagnoses_pkey; Type: CONSTRAINT; Schema: public; Owner: clinic
--

ALTER TABLE ONLY public.diagnoses
    ADD CONSTRAINT diagnoses_pkey PRIMARY KEY (diagnosis_id);


--
-- TOC entry 3242 (class 2606 OID 16416)
-- Name: diagnosis_appointment diagnosis_appointment_pkey; Type: CONSTRAINT; Schema: public; Owner: clinic
--

ALTER TABLE ONLY public.diagnosis_appointment
    ADD CONSTRAINT diagnosis_appointment_pkey PRIMARY KEY (diag_app_id);


--
-- TOC entry 3244 (class 2606 OID 16422)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: clinic
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (role_id);


--
-- TOC entry 3246 (class 2606 OID 16432)
-- Name: roles ukofx66keruapi6vyqpv6f2or37; Type: CONSTRAINT; Schema: public; Owner: clinic
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name);


--
-- TOC entry 3248 (class 2606 OID 16430)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: clinic
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- TOC entry 3250 (class 2606 OID 16438)
-- Name: appointments fk95vepu86o8syqtux9gkr71bhy; Type: FK CONSTRAINT; Schema: public; Owner: clinic
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT fk95vepu86o8syqtux9gkr71bhy FOREIGN KEY (animal_id) REFERENCES public.animals(animal_id);


--
-- TOC entry 3252 (class 2606 OID 16448)
-- Name: diagnosis_appointment fkfb1hky5nx0cmyxxyr7lq3w7lw; Type: FK CONSTRAINT; Schema: public; Owner: clinic
--

ALTER TABLE ONLY public.diagnosis_appointment
    ADD CONSTRAINT fkfb1hky5nx0cmyxxyr7lq3w7lw FOREIGN KEY (appointment_id) REFERENCES public.appointments(id);


--
-- TOC entry 3251 (class 2606 OID 16443)
-- Name: appointments fkflxgtakjdxnyvpu2krujv343i; Type: FK CONSTRAINT; Schema: public; Owner: clinic
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT fkflxgtakjdxnyvpu2krujv343i FOREIGN KEY (vet_id) REFERENCES public.users(user_id);


--
-- TOC entry 3249 (class 2606 OID 16433)
-- Name: animals fkhpcrtp144xytkvtb001js3ldp; Type: FK CONSTRAINT; Schema: public; Owner: clinic
--

ALTER TABLE ONLY public.animals
    ADD CONSTRAINT fkhpcrtp144xytkvtb001js3ldp FOREIGN KEY (owner_id) REFERENCES public.users(user_id);


--
-- TOC entry 3253 (class 2606 OID 16453)
-- Name: diagnosis_appointment fkl4j0y281yo8nosbx2yl2alctj; Type: FK CONSTRAINT; Schema: public; Owner: clinic
--

ALTER TABLE ONLY public.diagnosis_appointment
    ADD CONSTRAINT fkl4j0y281yo8nosbx2yl2alctj FOREIGN KEY (diagnosis_id) REFERENCES public.diagnoses(diagnosis_id);


--
-- TOC entry 3254 (class 2606 OID 16458)
-- Name: users fkp56c1712k691lhsyewcssf40f; Type: FK CONSTRAINT; Schema: public; Owner: clinic
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkp56c1712k691lhsyewcssf40f FOREIGN KEY (role_id) REFERENCES public.roles(role_id);


-- Completed on 2025-03-02 22:40:55

--
-- PostgreSQL database dump complete
--

